### ISSUE TITLE
Please bump golang.org/x/sys dependency version

### ISSUE THREAD

**Issue by clausecker** [ambientsound/visp#10]
This package depends on a version of golang.org/x/sys too outdated to support recent platforms such as riscv64-freebsd.  Please bump the dependency to support a build on these platforms.

**Comment by kimtore** [comment]
@clausecker, thanks for reporting. Can you try the latest release and see if that fixes the issue for you?

**Comment by clausecker** [comment]
I can confirm that the project builds fine on risc64-freebsd as per commit 1b80eca.  The test suite passes, too.
