### ISSUE TITLE
Error in authenticating

### ISSUE THREAD

**Issue by dfangx** [ambientsound/visp#2]
I get an error when running `:auth <code>`:

Update player: Only valid bearer authentication supported

Using default configuration with .config/visp directory created. Any help is appreciated

**Comment by kimtore** [comment]
Did you go to https://visp.site/authorize, log in to Spotify, and copy the token? It should look something like this:

```
:auth eyJ...<long string of letters>
```

If you did this already, try looking at `~/.config/visp/token.json`. Does the file exist and look something like this?

```
{
  "access_token": "SECRET",
  "token_type": "Bearer",
  "refresh_token": "SECRET",
  "expiry": "2021-04-23T22:08:45.530966523Z"
}
```

**Comment by dfangx** [comment]
My token was not very long, less than 10 characters. After logging in to Spotify, it redirected me to visp.site callback. I do not see any token.json file.

**Comment by kimtore** [comment]
Looks like there was some kind of error, tokens are very long, around 600 characters. Try going to that page again and click _authorize_, see if you get the token then.

**Comment by dfangx** [comment]
Ok I just tried it using a clean Firefox profile. Seems like it had something to do with my hardened setup. It works now. Thanks!

**Comment by kimtore** [comment]
You're welcome, enjoy :)

**Comment by kimtore** [comment]
If you don't mind, maybe you can open up the debugging console in your hardened setup and see if you get any error messages while doing the whole authentication path. This might affect other users and adding additional security measures in the authorization server would be much welcome.

**Comment by dfangx** [comment]
Turns out it was because I was cleaning my cookies every time I switched sites. Making sure the cookies don't get wiped during the authentication process solved the issue.

**Comment by kimtore** [comment]
Thanks for investigating. The cookie is an extra security measure to ensure to my auth server that only the client that initiated the login to Spotify can get the access token for that request, so I don't want to disable that. But if more users have trouble it might be worth documenting or looking at alternatives.
