### ISSUE TITLE
:help command not working on darwin

### ISSUE THREAD

**Issue by jradek** [ambientsound/visp#4]
Hi,

I'm running the latest release (`d2efc0e`) on darwin.

## Bug
When I enter the command
```
:help
```
as documented [here](https://github.com/ambientsound/visp/blob/master/doc/intro.md#user-guide), the output `not a command: help` appears. 

So only `<F1>` works, to open the help/key bindings.

### Expected behavior

1. `:help` behaves as `<F1>`.
1. **or** update documentation

**Comment by kimtore** [comment]
Hi @jradek,
Thanks for reporting.
There is an error in the documentation, please use `show keybindings` instead.
