### ISSUE TITLE
spotify authorization no longer possible

### ISSUE THREAD

**Issue by jradek** [ambientsound/visp#5]
Hi,

my spotify token expired a couple of hours ago.
I tried to get a new one by visiting https://visp.site/authorize, but this no longer seems to work. It constantly reports `Authorization failed`.
I also tried to disable the app `visp` in spotify and readded it. However, it is no longer possible to get a new token.

### environment
darwin (latest)

**Comment by jradek** [comment]
Suddenly, it works again. Maybe this was a spotify issue.

**Comment by kimtore** [comment]
Spotify was having some issues yesterday. I reported this to the Spotify Go library maintainers at https://github.com/zmb3/spotify/issues/153. There is also some info at https://community.spotify.com/t5/Spotify-for-Developers/Constant-503-errors-from-API/td-p/5203816.
