### ISSUE TITLE
HTTP 413 Request Entity Too Large

### ISSUE THREAD

**Issue by muydipalma** [ambientsound/visp#6]
Hi! Beatiful work, very compact and fast compared to spoti tui. i tried visp cuz in spt i cant visualize my "liked songs" entirily, but now i have the problem with this playlist with 800+ songs, i cant play any song.

i get this message:

spotify: HTTP 413 Request Entity Too Large (body empty)

This only happens with my "Saved Tracks" wich has 835 songs, i tried to play a 484 song playlist and have a "bad getaway" message, but works anyway

thanks for the work!

**Comment by kimtore** [comment]
Hi @muydipalma,

Thanks for the kind feedback and the bug report.
When playing a list, Visp sends all the tracks to be queued up, but Spotify has some limits. I will take a look at this after the weekend when I get home.

A workaround while waiting: copy a smaller number of tracks using `y`, when make a new list (`<C-w>c`), paste it with `p`, and then play the tracks. Sorry for the inconvenience.

**Comment by muydipalma** [comment]
No problem! Love your work, one more little thing... i couldnt find a shuffle toggle, any workaround?

Thanks in advance for you time!

**Comment by kimtore** [comment]
This issue should be fixed now. There is an artificial limit on how many tracks can be added at a time. Visp didn't know about this, so now it is set to 750. This seems to work for me. If you still have problems, I can add an option so you might tweak it yourself.

As for shuffle, I can add this presently.

**Comment by kimtore** [comment]
@muydipalma,

Shuffle support was added in commit b3c2654b3e592c33803cd2afe959c8b83639074b and the default binding to toggle it is `s`.
