### ISSUE TITLE
"Illegal offset: should be position XOR uri"

### ISSUE THREAD

**Issue by quunnb** [ambientsound/visp#9]
I get the above error whenever I press `<Enter>` on a song or do `:play selection`. Am I doing or understanding something wrong? I can add songs to que though play them that way. I've tried st and alacritty.

**Comment by kimtore** [comment]
Hi @demiaus,
This has worked correctly in the past. I suspect that Spotify has changed some upstream API's, and now it's broken for Visp.
The library Visp uses to speak with this API has been updated, but there are some breaking changes along the way.
I'll see what can be done.

**Comment by kimtore** [comment]
Apparently an issue upstream: zmb3/spotify#219
